// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACfxrZ-QwJfXoV4tHGgnmLXAs3LBTwOYQ',
    appId: '1:330943389157:android:6b89505c59c2634f4aa30c',
    messagingSenderId: '330943389157',
    projectId: 'projectappmobile-ea8ed',
    storageBucket: 'projectappmobile-ea8ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8NrnhxtIS1boKgPiXgV09NxujtZVvTw',
    appId: '1:330943389157:ios:63470ece8329c9e34aa30c',
    messagingSenderId: '330943389157',
    projectId: 'projectappmobile-ea8ed',
    storageBucket: 'projectappmobile-ea8ed.appspot.com',
    androidClientId: '330943389157-furd4so7nqdoppau61ue274cjjrprg2h.apps.googleusercontent.com',
    iosClientId: '330943389157-l02gqc2p79qe6ru68uhj4qe7ki5d83sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
